version: '3.9'

services:
  spring_app:
    container_name: spring_app
    image: spring_postgres
    build: .
    ports:
      - "8080:8080"
    environment:
#      - DATABASE_URL=jdbc:postgresql://dpg-ckhdukcldqrs739lcov0-a/database_2olf
#      - DATABASE_USERNAME=database_2olf_user
#      - DATABASE_PASSWORD=K8QzfH0KE6XmJX1bsHnCPj4Ex4Yy1JGs
      - DATABASE_URL=jdbc:postgresql://postgres_db:5432/test_jwt_new
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=reze
    depends_on:
      postgres_db:
        condition: service_healthy

  postgres_db:
    container_name: postgres_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: reze
      POSTGRES_DB: test_jwt_new
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5