version: '3.9'

services:
  spring_app:
    container_name: spring_app
    image: spring_postgres
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://dpg-cmda1s0cmk4c73ajofgg-a.oregon-postgres.render.com/zeddit_db
#      - DATABASE_URL=jdbc:postgresql://postgres_db:5432/social
      - DATABASE_USERNAME=zeddit_db_user
      - DATABASE_PASSWORD=x1pO51NQsPTurb95dQNax0jf4ycIJckk
    depends_on:
      postgres_db:
        condition: service_healthy

  postgres_db:
    container_name: postgres_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: zeddit_db_user
      POSTGRES_PASSWORD: x1pO51NQsPTurb95dQNax0jf4ycIJckk
      POSTGRES_DB: zeddit_db
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5